import { Category } from "./model";

export const DEFAULT_SYSTEM_CATEGORIES: Category[] = [
  {
    id: "general",
    name: "General",
    active: true,
    system: true,
    sortOrder: 1,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "minuman",
    name: "Minuman",
    active: true,
    system: true,
    sortOrder: 2,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "makanan",
    name: "Makanan",
    active: true,
    system: true,
    sortOrder: 3,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "snack",
    name: "Snack",
    active: true,
    system: true,
    sortOrder: 4,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "frozen-food",
    name: "Frozen Food",
    active: true,
    system: true,
    sortOrder: 5,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "sembako",
    name: "Sembako",
    active: true,
    system: true,
    sortOrder: 6,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "bumbu",
    name: "Bumbu",
    active: true,
    system: true,
    sortOrder: 7,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "buah-sayur",
    name: "Buah & Sayur",
    active: true,
    system: true,
    sortOrder: 8,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "daging",
    name: "Daging",
    active: true,
    system: true,
    sortOrder: 9,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "alat-tulis",
    name: "Alat Tulis",
    active: true,
    system: true,
    sortOrder: 10,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "laptop-elektronik",
    name: "Laptop/Elektronik",
    active: true,
    system: true,
    sortOrder: 11,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "handphone-aksesoris",
    name: "Handphone & Aksesoris",
    active: true,
    system: true,
    sortOrder: 12,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "listrik",
    name: "Listrik",
    active: true,
    system: true,
    sortOrder: 13,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "perkakas",
    name: "Perkakas",
    active: true,
    system: true,
    sortOrder: 14,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "bangunan",
    name: "Bangunan",
    active: true,
    system: true,
    sortOrder: 15,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "alkes",
    name: "Alat Kesehatan",
    active: true,
    system: true,
    sortOrder: 16,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "obat",
    name: "Obat",
    active: true,
    system: true,
    sortOrder: 17,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "kosmetik",
    name: "Kosmetik",
    active: true,
    system: true,
    sortOrder: 18,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "pakan",
    name: "Pakan",
    active: true,
    system: true,
    sortOrder: 19,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "pet-shop",
    name: "Pet Shop",
    active: true,
    system: true,
    sortOrder: 20,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "fashion",
    name: "Fashion",
    active: true,
    system: true,
    sortOrder: 21,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "otomotif",
    name: "Otomotif",
    active: true,
    system: true,
    sortOrder: 22,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "sparepart",
    name: "Sparepart",
    active: true,
    system: true,
    sortOrder: 23,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "lainnya",
    name: "Lainnya",
    active: true,
    system: true,
    sortOrder: 24,
    createdAt: 0,
    updatedAt: 0,
  },
];
