import { Unit } from "./model";

export const DEFAULT_SYSTEM_UNITS: Unit[] = [
  {
    id: "pcs",
    name: "PCS",
    symbol: "pcs",
    allowDecimal: false,
    active: true,
    system: true,
    sortOrder: 1,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "box",
    name: "BOX",
    symbol: "box",
    allowDecimal: false,
    active: true,
    system: true,
    sortOrder: 2,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "pack",
    name: "PACK",
    symbol: "pack",
    allowDecimal: false,
    active: true,
    system: true,
    sortOrder: 3,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "botol",
    name: "BOTOL",
    symbol: "btl",
    allowDecimal: true,
    active: true,
    system: true,
    sortOrder: 4,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "kaleng",
    name: "KALENG",
    symbol: "klg",
    allowDecimal: true,
    active: true,
    system: true,
    sortOrder: 5,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "liter",
    name: "LITER",
    symbol: "L",
    allowDecimal: true,
    active: true,
    system: true,
    sortOrder: 6,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "kilogram",
    name: "KILOGRAM",
    symbol: "kg",
    allowDecimal: true,
    active: true,
    system: true,
    sortOrder: 7,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "gram",
    name: "GRAM",
    symbol: "g",
    allowDecimal: true,
    active: true,
    system: true,
    sortOrder: 8,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "meter",
    name: "METER",
    symbol: "m",
    allowDecimal: true,
    active: true,
    system: true,
    sortOrder: 9,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "roll",
    name: "ROLL",
    symbol: "roll",
    allowDecimal: true,
    active: true,
    system: true,
    sortOrder: 10,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "lusin",
    name: "LUSIN",
    symbol: "lusin",
    allowDecimal: false,
    active: true,
    system: true,
    sortOrder: 11,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "karung",
    name: "KARUNG",
    symbol: "krg",
    allowDecimal: false,
    active: true,
    system: true,
    sortOrder: 12,
    createdAt: 0,
    updatedAt: 0,
  },
];
